### ISSUE TITLE
packages.lisp exports

### ISSUE THREAD

**Issue by jgarte** [s-expressionists/Invistra#1]
Hi,

Does this mean that there are currently no exports in the Invistra package?

https://github.com/s-expressionists/Invistra/blob/main/code/packages.lisp#L3

Should we add a TODO to export the API for Invistra?

**Comment by yitzchak** [comment]
It implements CL:FORMAT and it is not currently complete anyways. It doesn't have an intrinsic/extrinsic API yet either. Basically, I need to finish ironing out the API between Incless and Inravina. In short, Invistra isn't usable outside of SICL yet.
